spring:
  application:
    name: franchise-hub-api
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
  
  datasource:
    url: jdbc:sqlite:franchise_hub.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 

server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:4200
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.franchisehub.api: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: FranchiseHub API
    description: Comprehensive REST API for FranchiseHub Application
    version: 1.0.0
    contact:
      name: FranchiseHub Team
      email: support@franchisehub.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:franchise_hub_dev.db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/franchise_hub?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:franchise_user}
    password: ${DB_PASSWORD:franchise_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.franchisehub.api: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: "jdbc:sqlite::memory:"
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never
